-- Criação do banco de dados
CREATE DATABASE mecanica;
USE mecanica;

-- 1. Criação da tabela CLIENTE
CREATE TABLE CLIENTE (
    idCLIENTE INT PRIMARY KEY,
    Nome VARCHAR(45),
    CPF_CNPJ VARCHAR(45),
    Telefone VARCHAR(45),
    Endereco VARCHAR(45)
);

-- 2. Criação da tabela VEICULO
CREATE TABLE VEICULO (
    idVEICULO INT PRIMARY KEY,
    PLACA VARCHAR(45),
    MODELO VARCHAR(45),
    ANO INT,
    MARCA VARCHAR(45),
    COR VARCHAR(45),
    CLIENTE_idCLIENTE INT,
    FOREIGN KEY (CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE)
);

-- 3. Criação da tabela MECANICO
CREATE TABLE MECANICO (
    idMECANICO INT PRIMARY KEY,
    Nome VARCHAR(45),
    Endereco VARCHAR(45),
    Especialidade VARCHAR(45)
);

-- 4. Criação da tabela ORDEM_SERVICO
CREATE TABLE ORDEM_SERVICO (
    idORDEM_SERVICO INT PRIMARY KEY,
    Data_de_Emissao DATE,
    Data_de_Conclusao DATE,
    Status VARCHAR(45),
    Valor_Total DECIMAL(11,2),
    VEICULO_idVEICULO INT,
    VEICULO_CLIENTE_idCLIENTE INT,
    MECANICO_idMECANICO INT,
    FOREIGN KEY (VEICULO_idVEICULO) REFERENCES VEICULO(idVEICULO),
    FOREIGN KEY (VEICULO_CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE),
    FOREIGN KEY (MECANICO_idMECANICO) REFERENCES MECANICO(idMECANICO)
);

-- 5. Criação da tabela SERVICO
CREATE TABLE SERVICO (
    idSERVICO INT PRIMARY KEY,
    Descricao VARCHAR(45),
    Valor_da_Mao_de_Obra DECIMAL(11,2)
);

-- 6. Criação da tabela ORDEM_SERVICO_POSSUI_SERVICOS
CREATE TABLE ORDEM_SERVICO_POSSUI_SERVICOS (
    ORDEM_SERVICO_idORDEM_SERVICO INT,
    ORDEM_SERVICO_VEICULO_idVEICULO INT,
    ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE INT,
    SERVICO_idSERVICO INT,
    FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO(idORDEM_SERVICO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_idVEICULO) REFERENCES VEICULO(idVEICULO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE),
    FOREIGN KEY (SERVICO_idSERVICO) REFERENCES SERVICO(idSERVICO)
);

-- 7. Criação da tabela PECA
CREATE TABLE PECA (
    idPECA INT PRIMARY KEY,
    Descricao VARCHAR(45),
    Valor_Unitario DECIMAL(11,2)
);

-- 8. Criação da tabela ORDEM_SERVICO_USA_PECAS
CREATE TABLE ORDEM_SERVICO_USA_PECAS (
    PECA_idPECA INT,
    ORDEM_SERVICO_idORDEM_SERVICO INT,
    ORDEM_SERVICO_VEICULO_idVEICULO INT,
    ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE INT,
    FOREIGN KEY (PECA_idPECA) REFERENCES PECA(idPECA),
    FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO(idORDEM_SERVICO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_idVEICULO) REFERENCES VEICULO(idVEICULO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE)
);

-- 9. Criação da tabela MECANICO_EXECUTA_ORDEM_SERVICO
CREATE TABLE MECANICO_EXECUTA_ORDEM_SERVICO (
    MECANICO_idMECANICO INT,
    ORDEM_SERVICO_idORDEM_SERVICO INT,
    ORDEM_SERVICO_VEICULO_idVEICULO INT,
    ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE INT,
    FOREIGN KEY (MECANICO_idMECANICO) REFERENCES MECANICO(idMECANICO),
    FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO) REFERENCES ORDEM_SERVICO(idORDEM_SERVICO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_idVEICULO) REFERENCES VEICULO(idVEICULO),
    FOREIGN KEY (ORDEM_SERVICO_VEICULO_CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE)
);
